# Default state for all rules
default: true

# MD007/ul-indent - Unordered list indentation
MD007:
  # Spaces for indent
  indent: 2

# MD013/line-length - Line length
MD013:
  line_length: 200
  tables: false
  code_blocks: false

# MD026/no-trailing-punctuation - Trailing punctuation in heading
MD026:
  # Punctuation characters
  punctuation: ".,;:!。，；：！"

# MD029/ol-prefix - Ordered list item prefix
MD029:
  style: ordered

# MD033/no-inline-html - Inline HTML
MD033: false

# MD036/no-emphasis-as-heading/no-emphasis-as-header - Emphasis used instead of a heading
MD036: false

# MD041/first-line-heading/first-line-h1 - First line in a file should be a top-level heading
MD041: false
