extends: default
rules:
  empty-lines:
    max: 1
    max-start: 0
    max-end: 0
  new-lines:
    level: warning
    type: unix
  line-length:
    max: 150
  comments:
    min-spaces-from-content: 1
  document-start: false
  document-end: false
  new-line-at-end-of-file: enable
