# Configuration file for MegaLinter
#
# See all available variables at https://megalinter.io/latest/config-file/ and in linters documentation

# all, none, or list of linter keys
APPLY_FIXES: none # all, none, or list of linter keys
ENABLE_LINTERS: # If you use ENABLE_LINTERS variable, all other linters will be disabled by default
  - COPYPASTE_JSCPD             # https://megalinter.io/latest/descriptors/copypaste_jscpd/
  - GO_GOLANGCI_LINT            # https://megalinter.io/latest/descriptors/go_golangci_lint/
  - JSON_PRETTIER               # https://megalinter.io/latest/descriptors/json_prettier/
  - MARKDOWN_MARKDOWNLINT       # https://megalinter.io/latest/descriptors/markdown_markdownlint/
  - REPOSITORY_CHECKOV          # https://megalinter.io/latest/descriptors/repository_checkov/
  - SPELL_CSPELL                # https://megalinter.io/latest/descriptors/spell_cspell/
  - YAML_YAMLLINT               # https://megalinter.io/latest/descriptors/yaml_yamllint/
SHOW_ELAPSED_TIME: true
FILEIO_REPORTER: false
LINTER_RULES_PATH: .linters
PRINT_ALPACA: false
FORMATTERS_DISABLE_ERRORS: false
REPORT_OUTPUT_FOLDER: /tmp/lint/.ml-reports
CONFIG_REPORTER: false # Activates/deactivates the config file to integrate with vscode
UPDATED_SOURCES_REPORTER: false
EXCLUDED_DIRECTORIES:
  - .archived
  - docs
  - examples

# Add specific linters variables configuration
# e.g. MARKDOWN_MARKDOWNLINT_CONFIG_FILE: .markdownlint.yml

# MARKDOWN_MARKDOWNLINT variables
MARKDOWN_MARKDOWNLINT_CONFIG_FILE: .markdownlint.yml

# YAML_YAMLLINT variables
YAML_YAMLLINT_CONFIG_FILE: .yamllint.yml

# JSON_PRETTIER variables
JSON_PRETTIER_CONFIG_FILE: .prettierrc.yml

# GO_GOLANGCI_LINT
GO_GOLANGCI_LINT_CONFIG_FILE: .golangci.yml
