name: CI

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

permissions:
  contents: read
  security-events: write

jobs:
  build:
    name: Go Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: ./.github/actions/setup-go
      - run: go build -v ./...

  lint:
    name: MegaLinter
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: MegaLinter
        uses: oxsecurity/megalinter/flavors/go@v8.7.0
        id: ml
        env:
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_WORKSPACE: ${{ github.workspace }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Archive reports
        uses: actions/upload-artifact@v4
        if: ${{ success() || failure() }}
        with:
          name: MegaLinter reports
          path: |
            .ml-reports/
            mega-linter.log

  unit-test:
    name: Go Unit Tests
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-go
        with:
          go-version: '1.24'
      - run: go test ./... -v -coverprofile=unit-test.lcov -json > unit-test.log
      - uses: actions/upload-artifact@v4
        with:
          name: unit-test-reports-${{ github.sha }}
          path: |
            unit-test.lcov
            unit-test.log
          retention-days: 7
          overwrite: true

  acceptance-test:
    name: Go Acceptance Tests
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        tf-version: ['1.11.*', '1.12.*']
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-go
        with:
          go-version: '1.24'
      - uses: hashicorp/setup-terraform@v3.1.1
        with:
          terraform_version: ${{ matrix.tf-version }}
          terraform_wrapper: false
      - run: go test ./internal/provider -v -coverprofile=acc-test.lcov -json > acc-test.log
        env:
          TF_ACC: '1'
      - uses: actions/upload-artifact@v4
        with:
          name: acc-test-reports-${{ github.sha }}
          path: |
            acc-test.lcov
            acc-test.log
          retention-days: 7
          overwrite: true

  sonar:
    name: SonarCloud Scan
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    needs: [unit-test, acceptance-test]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/download-artifact@v4
        with:
          name: unit-test-reports-${{ github.sha }}
      - uses: actions/download-artifact@v4
        with:
          name: acc-test-reports-${{ github.sha }}
      - uses: SonarSource/sonarqube-scan-action@v5.2.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  codeql:
    name: CodeQL Scan
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: github/codeql-action/init@v3
        with:
          languages: go
      - uses: github/codeql-action/analyze@v3
        with:
          category: '/language:go'
