name: ff-merge
run-name: '🔀 Fast-Forward Merge - ${{ github.ref_name }}'

on:
  pull_request: # Trigger action only on pull-requests
    types:
      - synchronize
      - opened
      - reopened

permissions:
  contents: read

jobs:
  check-ffnes:
    name: Check Fast-Forwardness
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 💻
        uses: actions/checkout@v4.1.7

      - name: Check Fast-Forwardness 🚀
        run: |
          git fetch origin ${{ github.head_ref }}:refs/remotes/origin/${{ github.head_ref }}
          git merge-base --is-ancestor origin/${{ github.head_ref }} ${{ github.base_ref }}
          if [ $? -ne 0 ]; then
            echo "This PR is not fast-forwardable. Please rebase your branch."
            exit 1
          else
            echo "This PR is fast-forwardable."
          fi

